Vagrant.configure("2") do |config|
  config.vm.define :clienteFw do |clienteFw|
    clienteFw.vm.box = "bento/centos-7"
    clienteFw.vm.network :public_network, ip: "192.168.0.30"
    clienteFw.vm.hostname = "clienteFw"
  end
  
  config.vm.define :firewall do |firewall|
    firewall.vm.box = "miguel-rondon/vm_firewall"
    firewall.vm.box_version = "0.0.3"
    firewall.vm.network :public_network, ip: "192.168.0.16"
    firewall.vm.network :private_network, ip: "192.168.100.3"
    firewall.vm.provision "shell", path: "firewall.sh"
    firewall.vm.hostname = "firewall"
  end
  
  config.vm.define :servidor2 do |servidor2|
    servidor2.vm.box = "miguel-rondon/vm_server"
    servidor2.vm.box_version = "0.0.9"
    servidor2.vm.network :private_network, ip: "192.168.100.4"
    servidor2.vm.hostname = "servidor2"
  end
  
  config.vm.define :servdns do |servdns|
    servdns.vm.box = "miguel-rondon/servdns"
    servdns.vm.box_version = "0.0.1"
    servdns.vm.network :private_network, ip: "192.168.100.5"
    servdns.vm.hostname = "servdns"
  end
  
end